CREATE TABLE `partner_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`partnerName` varchar(255) NOT NULL,
	`partnerEmail` varchar(320) NOT NULL,
	`partnerCompany` varchar(255),
	`title` varchar(512) NOT NULL,
	`category` varchar(255),
	`submissionType` enum('guest_post','link_insertion') NOT NULL DEFAULT 'guest_post',
	`contentText` text,
	`contentFileKey` varchar(1024),
	`googleDocsUrl` varchar(1024),
	`targetArticleUrl` varchar(1024),
	`declaredLinks` json NOT NULL DEFAULT (JSON_ARRAY()),
	`status` enum('pending','in_review','approved','rejected','published') NOT NULL DEFAULT 'pending',
	`reviewNotes` text,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`linkQaStatus` enum('pass','warn','fail'),
	`linkQaDetails` text,
	`wpPostId` int,
	`wpPostUrl` varchar(1024),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `partner_submissions_id` PRIMARY KEY(`id`)
);
